---
title: "Monte Carlo Demo "
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
set.seed(123)
library(ggplot2)
u1 = runif(10000,0,1)
u2 = runif(10000,0,1)
u3 = runif(10000,0,1)
M= pmax(u1,u2,u3)
head(M)
ccombind = cbind(u1,u2,u3)
dat <- transform(ccombind,M= pmax(u1,u2,u3))

```


```{r}
hist(dat$M)
```


```{r}
total = sum(dat$M>0.75)/length(dat$M)
round(total, digits=3)
```

```{r}
set.seed(123)
library(ggplot2)
samp1 = rnorm(2000,0,1)
samp2 = rnorm(1000,1,sqrt(2))
plt_samp1 = ggplot(data.frame(samp1), aes(x=samp1)) + stat_bin(binwidth=0.25, position="identity")
plt_samp1
plt_samp2 = ggplot(data.frame(samp2), aes(x=samp2)) + stat_bin(binwidth=0.25, position="identity")
plt_samp2
combined = c(samp1, samp2)
plt2 = ggplot(data.frame(combined), aes(x=combined)) + stat_bin(binwidth=0.25, position="identity")
plt2
```

```{r}
set.seed(123)
n <- 100
theta <- 0.4
y <- rbinom(n, size=1, prob=theta)
print(y)
```
```{r}
yhat <- mean(y)
yhat
```
```{r}
a_0 <- b_0 <- 1
a_n <- sum(y) + a_0
a_n <- sum(y) + a_0
b_n <- n-sum(y) + b_0
a_n/(a_n+b_n)
```


```{r}
x <- seq(0, 1, length.out= 100)
f_y1 <- dbeta(x, shape1 = a_0, shape2 = b_0)
f_y2 <- dbeta(x, shape1 = a_n, shape2 = b_n)
plot(x, f_y1, ylim = range(f_y1, f_y2), type = "l", main ="Posterior and prior comparison", sub = "Simulated data result", xlab = expression(theta), ylab = "Probability density", lwd = 2)
lines(x, f_y2, lwd = 2, col = 2)
abline(v = theta, col = 3)

text(c(0.8, 0.3, theta), c(1.2, 3.5, 2), labels = c("p(theta)", "p(theta | y)", "true value"), col = 1:3) 
```



```{r}

pbeta(0.45, a_n, b_n, lower.tail = TRUE)

```
```{r}

qbeta(c(0.001, 0.991), a_n, b_n)
```


```{r}
set.seed(123)
sim_theta <- rbeta(5000, a_n, b_n)
hist(sim_theta, freq=FALSE, main = "Histogram of Monte Carlo samples", xlab = expression(theta), ylab = "Posterior density")
lines(density(sim_theta))
```


```{r}
set.seed(123)
mean(sim_theta)
```
```{r}
prob <- (mean(sim_theta>0.45))
prob
```




```{r}
quantile(sim_theta, c(0.001, 0.991))
```
